
services:
  realtime:
    container_name: realtime
    restart: always
    build:
      dockerfile: ./Dockerfile
    environment:
      - CLICKHOUSE_HOST=http://172.17.0.1:8123
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      bridge:
        ipv4_address: 172.30.0.10

    ports:
      - "9107:3000"

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16