
services:
  realtime:
    container_name: realtime
    restart: always
    build:
      dockerfile: ./Dockerfile
    environment:
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
    ports:
      - "9107:3000"
